// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crlxrluhbbxegvibqlwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNybHhybHVoYmJ4ZWd2aWJxbHdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0MjM1MTksImV4cCI6MjA1Njk5OTUxOX0.N44y900J4sgX6yhSSeuJlkN1-Oj-iMeWHgsOx25pqqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});